- api/src/main/resources/messages.properties
- omod/src/main/resources/apps/formentry_app.json
- updated manage forms extension to point to adminui configmetadata
> RA-835 Place Manage Forms in Adminui Configmetadata

- omod/src/main/java/org/openmrs/module/referenceapplication/page/controller/LoginPageController.java
Fixed a reflected XSS vulnerability on the login page that was exploitable by setting the referer to ```"><script>alert(0)</script><```.
> Fixed XSS Vulnerability

- LICENSE
Adding a license file according to the https://issues.openmrs.org/browse/GCI-6
> GCI-6: Adding a LICENSE file to the OpenMRS module

- omod/src/main/webapp/resources/scripts/manageApps.js
https://issues.openmrs.org/browse/RA-962
> RA-962: fixed issue deleting custom apps from the UI

- omod/src/main/compass/sass/login.scss
- omod/src/main/webapp/pages/login.gsp
https://issues.openmrs.org/browse/RA-222
> RA-222: Login button should be enabled at all times

- api/src/main/java/org/openmrs/module/referenceapplication/ReferenceApplicationActivator.java
- api/src/test/java/org/openmrs/module/referenceapplication/ReferenceApplicationActivatorComponentTest.java
- api/src/test/resources/ReferenceApplicationActivatorTestDataset.xml
- api/src/test/resources/test-hibernate.cfg.xml
- omod/src/main/resources/config.xml
- pom.xml
This PR refers to https://github.com/openmrs/openmrs-module-emrapi/pull/98
> MAP-19 reflect changes in emrapi module metadata

- omod/src/main/java/org/openmrs/module/referenceapplication/ReferenceApplicationWebConstants.java
- omod/src/main/java/org/openmrs/module/referenceapplication/page/controller/LoginPageController.java
- omod/src/test/java/org/openmrs/module/referenceapplication/page/controller/LoginPageControllerTest.java
https://issues.openmrs.org/browse/RA-1008
> RA-1008 changed loginPageController logic

- api/src/main/java/org/openmrs/module/referenceapplication/ReferenceApplicationActivator.java
- api/src/test/java/org/openmrs/module/referenceapplication/ReferenceApplicationActivatorComponentTest.java
- api/src/test/resources/ReferenceApplicationActivatorTestDataset.xml
- api/src/test/resources/test-hibernate.cfg.xml
- omod/src/main/resources/config.xml
- pom.xml
This PR depends on https://github.com/openmrs/openmrs-module-emrapi/pull/98, please do not merge it until it is merged.
> MAP-19 reflect changes in emrapi module metadata management

- omod/src/main/webapp/pages/login.gsp
Adding support for keyboard only login to the login page.
> RA-289: Allow login using only keyboard (without requiring mouse)

- omod/src/main/compass/sass/home.scss
- omod/src/main/webapp/pages/home.gsp
- omod/src/main/webapp/pages/login.gsp
- omod/src/main/webapp/pages/manageApps.gsp
- omod/src/main/webapp/pages/userApp.gsp
**This PR contains changes for the GSoC Project Bootstrap as a foundation for Ref App UI project.
It contains the following changes up to now**
Home Page css changes with media queries.
Login.gsp page bootstrap changes.
Home.gsp page bootstrap changes.
UserApp.gsp page bootstrap changes.
Bootstrap integration(Currently works with internet only).
**This PR will have more commit's when the project is going forward.**
Ticket ID :- RA-1952
> RA-1592 : Boostrap as a foundation for Reference Application UI Project.

- omod/src/main/java/org/openmrs/module/referenceapplication/filter/RequireLoginLocationFilter.java
- omod/src/main/java/org/openmrs/module/referenceapplication/page/controller/LoginPageController.java
- omod/src/main/resources/config.xml
- omod/src/main/webapp/pages/login.gsp
- omod/src/test/java/org/openmrs/module/referenceapplication/page/controller/LoginPageControllerTest.java
https://issues.openmrs.org/browse/RA-1624
> RA-1624: User login locations feature to support multiple locations.

- omod/src/main/java/org/openmrs/module/referenceapplication/page/controller/LoginPageController.java
- omod/src/test/java/org/openmrs/module/referenceapplication/page/controller/LoginPageControllerTest.java
https://issues.openmrs.org/browse/RA-1646
> RA-1646: 2-step login skips second page for single login location.

- pom.xml
Ticket :https://issues.openmrs.org/browse/RA-1688
> RA-1688 : update Ui commons version to reflect lastest ui commns changes

- omod/src/main/webapp/fragments/infoAndErrorMessages.gsp
Ticket ID:https://issues.openmrs.org/browse/RA-1752
Description
Added a flagged error message on the login page when the user signs in  with wrong credentials.The ticket ID contains the screen shots
> RA-1752: Fix invalid username / password message

- api/src/main/java/org/openmrs/module/referenceapplication/ReferenceApplicationActivator.java
Adding the ```@Override``` annotation for overriding and implementing methods
https://issues.openmrs.org/browse/RA-1817
> RA-1817: @Override used for overriding and implementing methods

- omod/src/main/java/org/openmrs/module/referenceapplication/page/controller/HomePageController.java
- omod/src/test/java/org/openmrs/module/referenceapplication/page/controller/HomePageControllerTest.java
https://issues.openmrs.org/browse/RA-1814
> RA-1814:Unnecessary imports should be removed

- omod/src/main/webapp/pages/login.gsp
link:https://issues.openmrs.org/browse/RA-1728
fix the Login button color
> RA-1728:fix the Login button color

- omod/src/main/webapp/pages/userApp.gsp
https://issues.openmrs.org/browse/RA-1898
> RA-1898 Change all 'emr.' message codes to 'coreapps.' equivalents

- pom.xml
Update POM dependencies from http to https
> Update POM dependencies from http to https

- omod/src/main/resources/styles/login.scss
- omod/src/main/webapp/pages/login.gsp
Added An Icon with Functionality of Show Password on Login Page
Issue link:   https://issues.openmrs.org/browse/RA-1902
> RA-1902: Add An Icon with Functionality of Showing Password on Login Page

- omod/src/main/java/org/openmrs/module/referenceapplication/page/controller/LoginPageController.java
Reverts openmrs/openmrs-module-referenceapplication#97
> Revert "RA-1958 - Force user to go to location selection screen"
